import React, { useState } from 'react';

const I = ({ d, className = 'w-4 h-4' }) => (
  <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor"
    strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">{d}</svg>
);
const XIcon       = p => <I {...p} d={<><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></>}/>;
const ShieldIcon  = p => <I {...p} d={<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>}/>;
const InfoIcon    = p => <I {...p} d={<><circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/></>}/>;

/* ── Social icons ── */
const TwitterIcon = ({ className }) => (
  <svg className={className} viewBox="0 0 24 24" fill="currentColor">
    <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/>
  </svg>
);
const InstagramIcon = ({ className }) => (
  <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <rect x="2" y="2" width="20" height="20" rx="5" ry="5"/>
    <circle cx="12" cy="12" r="4"/>
    <circle cx="17.5" cy="6.5" r="0.5" fill="currentColor"/>
  </svg>
);
const TikTokIcon = ({ className }) => (
  <svg className={className} viewBox="0 0 24 24" fill="currentColor">
    <path d="M19.59 6.69a4.83 4.83 0 0 1-3.77-4.25V2h-3.45v13.67a2.89 2.89 0 0 1-2.88 2.5 2.89 2.89 0 0 1-2.89-2.89 2.89 2.89 0 0 1 2.89-2.89c.28 0 .54.04.79.1V9.01a6.33 6.33 0 0 0-.79-.05 6.34 6.34 0 0 0-6.34 6.34 6.34 6.34 0 0 0 6.34 6.34 6.34 6.34 0 0 0 6.33-6.34V8.69a8.18 8.18 0 0 0 4.78 1.52V6.76a4.85 4.85 0 0 1-1.01-.07z"/>
  </svg>
);
const YoutubeIcon = ({ className }) => (
  <svg className={className} viewBox="0 0 24 24" fill="currentColor">
    <path d="M23.5 6.19a3.02 3.02 0 0 0-2.12-2.14C19.5 3.5 12 3.5 12 3.5s-7.5 0-9.38.55A3.02 3.02 0 0 0 .5 6.19C0 8.07 0 12 0 12s0 3.93.5 5.81a3.02 3.02 0 0 0 2.12 2.14C4.5 20.5 12 20.5 12 20.5s7.5 0 9.38-.55a3.02 3.02 0 0 0 2.12-2.14C24 15.93 24 12 24 12s0-3.93-.5-5.81zM9.75 15.5V8.5l6.5 3.5-6.5 3.5z"/>
  </svg>
);

/* ── Disclaimer Modal ── */
export function DisclaimerModal({ onClose }) {
  return (
    <>
      <div className="fixed inset-0 z-50" style={{ background: 'rgba(0,0,0,0.7)', backdropFilter: 'blur(10px)' }}
        onClick={onClose}/>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 pointer-events-none">
        <div className="w-full max-w-2xl rounded-3xl border border-white/10 overflow-hidden pointer-events-auto"
          style={{ background: 'rgba(6,9,20,0.99)', animation: 'disclaimerIn 0.3s cubic-bezier(0.16,1,0.3,1)', maxHeight: '90vh' }}>

          {/* Header */}
          <div className="flex items-center justify-between px-6 py-4 border-b border-white/[0.08]"
            style={{ background: 'rgba(255,255,255,0.02)' }}>
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-xl flex items-center justify-center"
                style={{ background: 'rgba(245,158,11,0.15)', border: '1px solid rgba(245,158,11,0.3)' }}>
                <ShieldIcon className="w-4 h-4 text-yellow-400"/>
              </div>
              <div>
                <p className="text-white font-black text-sm">Legal Disclaimer</p>
                <p className="text-slate-500 text-[11px]">Please read before using Scorina AI</p>
              </div>
            </div>
            <button onClick={onClose}
              className="w-8 h-8 rounded-xl flex items-center justify-center transition-all hover:bg-white/10"
              style={{ color: '#64748b' }}>
              <XIcon className="w-4 h-4"/>
            </button>
          </div>

          {/* Content */}
          <div className="overflow-y-auto px-6 py-5 space-y-5" style={{ maxHeight: 'calc(90vh - 130px)' }}>

            {/* Not gambling advice */}
            <div className="rounded-2xl border p-4"
              style={{ background: 'rgba(245,158,11,0.06)', borderColor: 'rgba(245,158,11,0.2)' }}>
              <p className="text-yellow-400 font-black text-sm mb-2">⚠️ Not Gambling or Betting Advice</p>
              <p className="text-slate-400 text-xs leading-relaxed">
                Scorina AI is an <strong className="text-white">entertainment and analytical platform only</strong>. 
                The predictions, statistics, and insights provided are generated by artificial intelligence models 
                and are intended solely for informational and entertainment purposes. 
                <strong className="text-white"> Nothing on this platform constitutes gambling advice, 
                betting tips, or financial recommendations</strong> of any kind.
              </p>
            </div>

            {/* Gambling laws */}
            <div className="rounded-2xl border border-white/[0.08] p-4"
              style={{ background: 'rgba(255,255,255,0.02)' }}>
              <p className="text-white font-black text-sm mb-2">🌍 Gambling Laws & Regulations</p>
              <p className="text-slate-400 text-xs leading-relaxed mb-3">
                Online gambling and sports betting are regulated differently across jurisdictions. 
                It is your sole responsibility to ensure that your use of any third-party betting or 
                gambling service complies with the laws applicable in your country, state, or region. 
                Scorina AI does not facilitate, promote, or endorse any form of real-money wagering.
              </p>
              <p className="text-slate-400 text-xs leading-relaxed">
                If you choose to use AI-generated predictions in conjunction with betting activities, 
                you do so entirely at your own risk. Scorina AI accepts no liability for any financial 
                losses, legal consequences, or damages arising from such use.
              </p>
            </div>

            {/* AI output disclaimer */}
            <div className="rounded-2xl border border-white/[0.08] p-4"
              style={{ background: 'rgba(255,255,255,0.02)' }}>
              <p className="text-white font-black text-sm mb-2">🤖 AI Output Accuracy</p>
              <p className="text-slate-400 text-xs leading-relaxed mb-3">
                All predictions and analyses are generated by machine learning models trained on 
                historical football data. These models do not have access to real-time injury news, 
                team selection, weather conditions, or other match-day variables that may materially 
                affect outcomes.
              </p>
              <p className="text-slate-400 text-xs leading-relaxed">
                <strong className="text-white">AI predictions are inherently probabilistic — they are never guarantees.</strong>{' '}
                Past accuracy does not guarantee future results. Scorina AI makes no warranty, 
                express or implied, regarding the accuracy, completeness, or fitness of any 
                AI-generated content for any particular purpose.
              </p>
            </div>

            {/* Responsible gaming */}
            <div className="rounded-2xl border p-4"
              style={{ background: 'rgba(16,185,129,0.05)', borderColor: 'rgba(16,185,129,0.15)' }}>
              <p className="text-emerald-400 font-black text-sm mb-2">💚 Responsible Gaming</p>
              <p className="text-slate-400 text-xs leading-relaxed mb-3">
                Gambling can be addictive and harmful. If you or someone you know is experiencing 
                problems with gambling, please seek help:
              </p>
              <div className="space-y-1.5">
                {[
                  { name: 'GamCare (UK)', url: 'https://www.gamcare.org.uk' },
                  { name: 'National Problem Gambling Helpline (US)', url: 'https://www.ncpgambling.org' },
                  { name: 'GambleAware', url: 'https://www.begambleaware.org' },
                  { name: 'Gambling Therapy', url: 'https://www.gamblingtherapy.org' },
                ].map((r, i) => (
                  <a key={i} href={r.url} target="_blank" rel="noopener noreferrer"
                    className="flex items-center gap-2 text-xs font-semibold transition-colors hover:text-emerald-400"
                    style={{ color: '#22d3ee' }}>
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 flex-shrink-0"/>
                    {r.name}
                  </a>
                ))}
              </div>
            </div>

            {/* Age restriction */}
            <div className="rounded-2xl border p-4"
              style={{ background: 'rgba(239,68,68,0.05)', borderColor: 'rgba(239,68,68,0.15)' }}>
              <p className="text-red-400 font-black text-sm mb-1">🔞 Age Restriction</p>
              <p className="text-slate-400 text-xs leading-relaxed">
                Scorina AI is intended for users aged <strong className="text-white">18 years and older</strong>. 
                By using this platform, you confirm that you are of legal age in your jurisdiction 
                to access sports analytics and prediction services.
              </p>
            </div>

            {/* Intellectual property */}
            <div className="rounded-2xl border border-white/[0.08] p-4"
              style={{ background: 'rgba(255,255,255,0.02)' }}>
              <p className="text-white font-black text-sm mb-2">© Intellectual Property</p>
              <p className="text-slate-400 text-xs leading-relaxed">
                All AI models, prediction algorithms, platform design, and content produced by 
                Scorina AI are proprietary. Football statistics and league data are sourced from 
                licensed third-party providers. Club names, logos, and trademarks belong to their 
                respective owners and are used for informational purposes only.
              </p>
            </div>

            <p className="text-slate-700 text-[10px] text-center pb-2">
              Last updated: March 2026 · By using Scorina AI you agree to these terms.
            </p>
          </div>

          {/* Footer */}
          <div className="px-6 py-4 border-t border-white/[0.07]">
            <button onClick={onClose}
              className="w-full py-3 rounded-xl font-black text-sm transition-all"
              style={{ background: 'linear-gradient(135deg,rgba(34,211,238,0.15),rgba(34,211,238,0.08))', border: '1px solid rgba(34,211,238,0.25)', color: '#22d3ee' }}>
              I understand — Continue to Scorina AI
            </button>
          </div>
        </div>
      </div>

      <style>{`
        @keyframes disclaimerIn { from{opacity:0;transform:scale(0.96) translateY(10px)} to{opacity:1;transform:scale(1) translateY(0)} }
      `}</style>
    </>
  );
}

/* ── Main Footer Component ── */
export default function Footer({ onNavigate }) {
  const [showDisclaimer, setShowDisclaimer] = useState(false);
  const year = new Date().getFullYear();

  const PLATFORM_LINKS = [
    { label: 'AI Analysis',    page: 'analysis'   },
    { label: 'Live Scores',    page: 'live'        },
    { label: 'Players',        page: 'players'     },
    { label: 'Managers',       page: 'managers'    },
    { label: 'Best Picks',     page: 'bestpicks'   },
    { label: 'Season Sim',     page: 'simulator'   },
    { label: 'My Picks',       page: 'pickem'      },
    { label: 'Leaderboard',    page: 'leaderboard' },
  ];

  const LEAGUE_LINKS = [
    { label: 'Premier League',  code: 'Premier League'  },
    { label: 'La Liga',         code: 'La Liga'         },
    { label: 'Bundesliga',      code: 'Bundesliga'      },
    { label: 'Serie A',         code: 'Serie A'         },
    { label: 'Ligue 1',         code: 'Ligue 1'         },
    { label: 'Primeira Liga',   code: 'Primeira Liga'   },
    { label: 'Champions League',code: 'Champions League'},
  ];

  const LEGAL_LINKS = [
    { label: 'Disclaimer',        action: () => setShowDisclaimer(true) },
    { label: 'Privacy Policy',    action: () => setShowDisclaimer(true) },
    { label: 'Terms of Use',      action: () => setShowDisclaimer(true) },
    { label: 'Responsible Gaming',action: () => setShowDisclaimer(true) },
    { label: 'Cookie Policy',     action: () => setShowDisclaimer(true) },
  ];

  const SOCIAL = [
    { name: 'X (Twitter)',  Icon: TwitterIcon,  href: 'https://twitter.com/scorinai',   color: '#1d9bf0' },
    { name: 'Instagram',    Icon: InstagramIcon, href: 'https://instagram.com/scorinai', color: '#e1306c' },
    { name: 'TikTok',       Icon: TikTokIcon,   href: 'https://tiktok.com/@scorinai',   color: '#ff0050' },
    { name: 'YouTube',      Icon: YoutubeIcon,  href: 'https://youtube.com/@scorinai',  color: '#ff0000' },
  ];

  return (
    <>
      {showDisclaimer && <DisclaimerModal onClose={() => setShowDisclaimer(false)}/>}

      <footer style={{ background: '#020407', borderTop: '1px solid rgba(255,255,255,0.06)', fontFamily: "'Outfit',sans-serif" }}>

        {/* Disclaimer banner */}
        <div className="border-b border-white/[0.05]" style={{ background: 'rgba(245,158,11,0.04)' }}>
          <div className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 py-3 flex items-center gap-3">
            <InfoIcon className="w-3.5 h-3.5 text-yellow-500 flex-shrink-0"/>
            <p className="text-slate-500 text-[11px] leading-relaxed flex-1">
              Scorina AI is for <strong className="text-slate-400">entertainment and analytics purposes only</strong>. 
              Not gambling advice. Predictions are AI-generated and do not guarantee outcomes. 18+ only.
            </p>
            <button onClick={() => setShowDisclaimer(true)}
              className="text-[11px] font-bold flex-shrink-0 transition-colors hover:text-yellow-400"
              style={{ color: '#f59e0b', textDecoration: 'underline', textUnderlineOffset: '2px' }}>
              Full Disclaimer
            </button>
          </div>
        </div>

        {/* Main footer body */}
        <div className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 py-12">
          <div className="grid grid-cols-2 md:grid-cols-5 gap-8 mb-12">

            {/* Brand column */}
            <div className="col-span-2 md:col-span-1">
              {/* Logo */}
              <div className="flex items-baseline gap-1 mb-4">
                <span className="text-2xl font-black text-white tracking-tight">Scorina</span>
                <div style={{
                  display:'inline-flex', alignItems:'center', justifyContent:'center',
                  background:'linear-gradient(135deg,#22d3ee,#a855f7)',
                  borderRadius:'7px', padding:'2px 7px', marginLeft:'3px',
                  boxShadow:'0 0 14px rgba(34,211,238,0.25)', position:'relative', top:'-2px',
                }}>
                  <span style={{ fontSize:'14px', fontWeight:900, color:'white', letterSpacing:'-0.04em', fontFamily:'JetBrains Mono,monospace' }}>AI</span>
                </div>
              </div>

              <p className="text-slate-600 text-xs leading-relaxed mb-5">
                AI-powered football analytics across Europe's top 7 leagues. 
                Predictions, live scores, player intelligence and fantasy picks — all in one place.
              </p>

              {/* Social icons */}
              <div className="flex items-center gap-2">
                {SOCIAL.map(s => (
                  <a key={s.name} href={s.href} target="_blank" rel="noopener noreferrer"
                    title={s.name}
                    className="w-8 h-8 rounded-xl flex items-center justify-center transition-all hover:scale-110"
                    style={{ background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.08)', color: '#475569' }}
                    onMouseEnter={e => { e.currentTarget.style.color = s.color; e.currentTarget.style.borderColor = `${s.color}40`; e.currentTarget.style.background = `${s.color}12`; }}
                    onMouseLeave={e => { e.currentTarget.style.color = '#475569'; e.currentTarget.style.borderColor = 'rgba(255,255,255,0.08)'; e.currentTarget.style.background = 'rgba(255,255,255,0.05)'; }}>
                    <s.Icon className="w-3.5 h-3.5"/>
                  </a>
                ))}
              </div>
            </div>

            {/* Platform */}
            <div>
              <p className="text-[10px] font-black text-slate-600 uppercase tracking-[0.18em] mb-4">Platform</p>
              <div className="space-y-2.5">
                {PLATFORM_LINKS.map((lk, i) => (
                  <button key={i} onClick={() => onNavigate(lk.page)}
                    className="block text-slate-500 text-xs transition-colors text-left hover:text-white w-full">
                    {lk.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Leagues */}
            <div>
              <p className="text-[10px] font-black text-slate-600 uppercase tracking-[0.18em] mb-4">Leagues</p>
              <div className="space-y-2.5">
                {LEAGUE_LINKS.map((lk, i) => (
                  <button key={i} onClick={() => onNavigate('league', lk.code)}
                    className="block text-slate-500 text-xs transition-colors text-left hover:text-white w-full">
                    {lk.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Legal */}
            <div>
              <p className="text-[10px] font-black text-slate-600 uppercase tracking-[0.18em] mb-4">Legal</p>
              <div className="space-y-2.5">
                {LEGAL_LINKS.map((lk, i) => (
                  <button key={i} onClick={lk.action}
                    className="block text-slate-500 text-xs transition-colors text-left hover:text-white w-full">
                    {lk.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Responsible gaming */}
            <div>
              <p className="text-[10px] font-black text-slate-600 uppercase tracking-[0.18em] mb-4">Support</p>
              <div className="space-y-2.5 mb-5">
                {[
                  { label: 'GamCare',          href: 'https://www.gamcare.org.uk'        },
                  { label: 'BeGambleAware',    href: 'https://www.begambleaware.org'     },
                  { label: 'Gambling Therapy', href: 'https://www.gamblingtherapy.org'   },
                  { label: 'GamStop (UK)',      href: 'https://www.gamstop.co.uk'         },
                ].map((r, i) => (
                  <a key={i} href={r.href} target="_blank" rel="noopener noreferrer"
                    className="block text-xs transition-colors hover:text-emerald-400"
                    style={{ color: '#475569' }}>
                    {r.label}
                  </a>
                ))}
              </div>
              {/* 18+ badge */}
              <div className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-xl border"
                style={{ background: 'rgba(239,68,68,0.08)', borderColor: 'rgba(239,68,68,0.2)' }}>
                <span className="text-red-400 font-black text-xs">18+</span>
                <span className="text-slate-600 text-[10px]">Only</span>
              </div>
            </div>
          </div>

          {/* Divider */}
          <div className="h-px mb-6" style={{ background: 'linear-gradient(90deg,transparent,rgba(255,255,255,0.07),transparent)' }}/>

          {/* Bottom row */}
          <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="flex flex-col sm:flex-row items-center gap-3 sm:gap-6">
              <p className="text-slate-700 text-[11px]">© {year} Scorina AI. All rights reserved.</p>
              <div className="hidden sm:block w-px h-3 bg-white/10"/>
              <p className="text-slate-700 text-[11px]">
                Data provided by{' '}
                <a href="https://www.api-football.com" target="_blank" rel="noopener noreferrer"
                  className="hover:text-slate-500 transition-colors underline underline-offset-2">
                  API-Football
                </a>
                {' '}·{' '}
                <a href="https://understat.com" target="_blank" rel="noopener noreferrer"
                  className="hover:text-slate-500 transition-colors underline underline-offset-2">
                  Understat
                </a>
              </p>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse"/>
              <p className="text-slate-700 text-[11px]">All systems operational</p>
            </div>
          </div>

          {/* Legal fine print */}
          <div className="mt-6 pt-6 border-t border-white/[0.04]">
            <p className="text-slate-700 text-[10px] leading-relaxed max-w-4xl">
              <strong className="text-slate-600">Disclaimer:</strong> Scorina AI provides football analytics and AI-generated predictions for entertainment purposes only. 
              This platform is not affiliated with any football league, club, or governing body. Club badges, names, and trademarks are the property of their 
              respective owners. Scorina AI does not promote or endorse gambling. If you use our predictions in conjunction with betting, you do so at your own risk. 
              Please gamble responsibly. 18+ only in jurisdictions where gambling is legal.
            </p>
          </div>
        </div>
      </footer>
    </>
  );
}
