// League standings data with team logos - REAL 2025-26 season data
// Last updated: February 4, 2026

export const leagueStandings = {
  'Premier League': [
    { rank: 1, team: 'Arsenal', logo: 'https://resources.premierleague.com/premierleague/badges/50/t3.png', played: 24, won: 16, drawn: 5, lost: 3, gf: 46, ga: 17, gd: 29, points: 53 },
    { rank: 2, team: 'Manchester City', logo: 'https://resources.premierleague.com/premierleague/badges/50/t43.png', played: 24, won: 14, drawn: 5, lost: 5, gf: 49, ga: 23, gd: 26, points: 47 },
    { rank: 3, team: 'Aston Villa', logo: 'https://resources.premierleague.com/premierleague/badges/50/t7.png', played: 24, won: 14, drawn: 4, lost: 6, gf: 35, ga: 26, gd: 9, points: 46 },
    { rank: 4, team: 'Manchester United', logo: 'https://resources.premierleague.com/premierleague/badges/50/t1.png', played: 24, won: 11, drawn: 8, lost: 5, gf: 44, ga: 36, gd: 8, points: 41 },
    { rank: 5, team: 'Chelsea', logo: 'https://resources.premierleague.com/premierleague/badges/50/t8.png', played: 24, won: 11, drawn: 7, lost: 6, gf: 42, ga: 27, gd: 15, points: 40 },
    { rank: 6, team: 'Liverpool', logo: 'https://resources.premierleague.com/premierleague/badges/50/t14.png', played: 24, won: 11, drawn: 6, lost: 7, gf: 39, ga: 33, gd: 6, points: 39 },
    { rank: 7, team: 'Brentford', logo: 'https://resources.premierleague.com/premierleague/badges/50/t94.png', played: 24, won: 11, drawn: 3, lost: 10, gf: 36, ga: 32, gd: 4, points: 36 },
    { rank: 8, team: 'Sunderland', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/77/Logo_Sunderland.svg/100px-Logo_Sunderland.svg.png', played: 24, won: 9, drawn: 9, lost: 6, gf: 27, ga: 26, gd: 1, points: 36 },
    { rank: 9, team: 'Fulham', logo: 'https://resources.premierleague.com/premierleague/badges/50/t54.png', played: 24, won: 10, drawn: 4, lost: 10, gf: 34, ga: 35, gd: -1, points: 34 },
    { rank: 10, team: 'Everton', logo: 'https://resources.premierleague.com/premierleague/badges/50/t11.png', played: 24, won: 9, drawn: 6, lost: 9, gf: 33, ga: 33, gd: 0, points: 33 },
    { rank: 11, team: 'Newcastle United', logo: 'https://resources.premierleague.com/premierleague/badges/50/t4.png', played: 24, won: 8, drawn: 9, lost: 7, gf: 40, ga: 43, gd: -3, points: 33 },
    { rank: 12, team: 'AFC Bournemouth', logo: 'https://resources.premierleague.com/premierleague/badges/50/t91.png', played: 24, won: 7, drawn: 10, lost: 7, gf: 34, ga: 32, gd: 2, points: 31 },
    { rank: 13, team: 'Brighton & Hove Albion', logo: 'https://resources.premierleague.com/premierleague/badges/50/t36.png', played: 24, won: 7, drawn: 8, lost: 9, gf: 35, ga: 33, gd: 2, points: 29 },
    { rank: 14, team: 'Tottenham Hotspur', logo: 'https://resources.premierleague.com/premierleague/badges/50/t6.png', played: 24, won: 7, drawn: 8, lost: 9, gf: 25, ga: 29, gd: -4, points: 29 },
    { rank: 15, team: 'Crystal Palace', logo: 'https://resources.premierleague.com/premierleague/badges/50/t31.png', played: 24, won: 6, drawn: 8, lost: 10, gf: 31, ga: 42, gd: -11, points: 26 },
    { rank: 16, team: 'Leeds United', logo: 'https://resources.premierleague.com/premierleague/badges/50/t2.png', played: 24, won: 7, drawn: 5, lost: 12, gf: 24, ga: 35, gd: -11, points: 26 },
    { rank: 17, team: 'Nottingham Forest', logo: 'https://resources.premierleague.com/premierleague/badges/50/t17.png', played: 24, won: 5, drawn: 5, lost: 14, gf: 29, ga: 48, gd: -19, points: 20 },
    { rank: 18, team: 'West Ham United', logo: 'https://resources.premierleague.com/premierleague/badges/50/t21.png', played: 24, won: 3, drawn: 6, lost: 15, gf: 25, ga: 47, gd: -22, points: 15 },
    { rank: 19, team: 'Burnley', logo: 'https://resources.premierleague.com/premierleague/badges/50/t90.png', played: 24, won: 1, drawn: 5, lost: 18, gf: 15, ga: 45, gd: -30, points: 8 },
    { rank: 20, team: 'Wolverhampton Wanderers', logo: 'https://resources.premierleague.com/premierleague/badges/50/t39.png', played: 24, won: 0, drawn: 2, lost: 22, gf: 11, ga: 54, gd: -43, points: 2 }
  ],
  
  'La Liga': [
    { rank: 1, team: 'Barcelona', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/47/FC_Barcelona_%28crest%29.svg/100px-FC_Barcelona_%28crest%29.svg.png', played: 22, won: 18, drawn: 1, lost: 3, gf: 60, ga: 23, gd: 37, points: 55 },
    { rank: 2, team: 'Real Madrid', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/100px-Real_Madrid_CF.svg.png', played: 22, won: 17, drawn: 3, lost: 2, gf: 47, ga: 18, gd: 29, points: 54 },
    { rank: 3, team: 'Atlético Madrid', logo: '/images/logos/laliga/Atletico_Madrid.png', played: 22, won: 13, drawn: 6, lost: 3, gf: 38, ga: 17, gd: 21, points: 45 },
    { rank: 4, team: 'Villarreal', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b9/Villarreal_CF_logo-en.svg/100px-Villarreal_CF_logo-en.svg.png', played: 21, won: 13, drawn: 3, lost: 5, gf: 39, ga: 23, gd: 16, points: 42 },
    { rank: 5, team: 'Real Betis', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/13/Real_betis_logo.svg/100px-Real_betis_logo.svg.png', played: 22, won: 9, drawn: 8, lost: 5, gf: 36, ga: 28, gd: 8, points: 35 },
    { rank: 6, team: 'Espanyol', logo: '/images/logos/laliga/Espanyol.png', played: 22, won: 10, drawn: 4, lost: 8, gf: 26, ga: 27, gd: -1, points: 34 },
    { rank: 7, team: 'Celta Vigo', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/RC_Celta_de_Vigo_logo.svg/100px-RC_Celta_de_Vigo_logo.svg.png', played: 22, won: 8, drawn: 9, lost: 5, gf: 29, ga: 23, gd: 6, points: 33 },
    { rank: 8, team: 'Real Sociedad', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Real_Sociedad_logo.svg/100px-Real_Sociedad_logo.svg.png', played: 22, won: 7, drawn: 7, lost: 8, gf: 30, ga: 30, gd: 0, points: 28 },
    { rank: 9, team: 'Osasuna', logo: '/images/logos/laliga/CA_Osasuna_2024_crest.svg.png', played: 22, won: 7, drawn: 5, lost: 10, gf: 26, ga: 27, gd: -1, points: 26 },
    { rank: 10, team: 'Alavés', logo: '/images/logos/laliga/Deportivo_Alaves.png', played: 22, won: 7, drawn: 4, lost: 11, gf: 20, ga: 27, gd: -7, points: 25 },
    { rank: 11, team: 'Athletic Club', logo:'/images/logos/laliga/athletic_bilbao.PNG', played: 22, won: 7, drawn: 4, lost: 11, gf: 21, ga: 31, gd: -10, points: 25 },
    { rank: 12, team: 'Girona', logo: '/images/logos/laliga/Girona_FC_Logo.png', played: 22, won: 6, drawn: 7, lost: 9, gf: 21, ga: 36, gd: -15, points: 25 },
    { rank: 13, team: 'Elche', logo: '/images/logos/laliga/Elche_CF_logo.png', played: 22, won: 5, drawn: 9, lost: 8, gf: 30, ga: 32, gd: -2, points: 24 },
    { rank: 14, team: 'Mallorca', logo: '/images/logos/laliga/Rcd_mallorca.png', played: 22, won: 6, drawn: 6, lost: 10, gf: 28, ga: 34, gd: -6, points: 24 },
    { rank: 15, team: 'Sevilla', logo: '/images/logos/laliga/Sevilla_FC_logo.png', played: 22, won: 7, drawn: 3, lost: 12, gf: 29, ga: 37, gd: -8, points: 24 },
    { rank: 16, team: 'Valencia', logo: '/images/logos/laliga/ValenciaCF.png', played: 22, won: 5, drawn: 8, lost: 9, gf: 23, ga: 35, gd: -12, points: 23 },
    { rank: 17, team: 'Getafe', logo: '/images/logos/laliga/Getafe_logo.png', played: 22, won: 6, drawn: 5, lost: 11, gf: 16, ga: 27, gd: -11, points: 23 },
    { rank: 18, team: 'Rayo Vallecano', logo: '/images/logos/laliga/Rayo_Vallecano_logo.png', played: 22, won: 5, drawn: 7, lost: 10, gf: 18, ga: 30, gd: -12, points: 22 },
    { rank: 19, team: 'Levante', logo: '/images/logos/laliga/Levante_Unión_Deportiva,_S.A.D._logo.png', played: 21, won: 4, drawn: 6, lost: 11, gf: 24, ga: 34, gd: -10, points: 18 },
    { rank: 20, team: 'Real Oviedo', logo: '/images/logos/laliga/Real_Oviedo_logo.png', played: 22, won: 3, drawn: 7, lost: 12, gf: 12, ga: 34, gd: -22, points: 16 }
  ],
  
  'Bundesliga': [
    { rank: 1, team: 'Bayern Munich', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg/100px-FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg.png', played: 20, won: 16, drawn: 3, lost: 1, gf: 74, ga: 18, gd: 56, points: 51 },
    { rank: 2, team: 'Borussia Dortmund', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/100px-Borussia_Dortmund_logo.svg.png', played: 20, won: 13, drawn: 6, lost: 1, gf: 41, ga: 19, gd: 22, points: 45 },
    { rank: 3, team: 'TSG Hoffenheim', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/TSG_1899_Hoffenheim_logo.svg/100px-TSG_1899_Hoffenheim_logo.svg.png', played: 20, won: 13, drawn: 3, lost: 4, gf: 43, ga: 23, gd: 20, points: 42 },
    { rank: 4, team: 'VfB Stuttgart', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/VfB_Stuttgart_1893_Logo.svg/100px-VfB_Stuttgart_1893_Logo.svg.png', played: 20, won: 12, drawn: 3, lost: 5, gf: 37, ga: 26, gd: 11, points: 39 },
    { rank: 5, team: 'RB Leipzig', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/04/RB_Leipzig_2014_logo.svg/100px-RB_Leipzig_2014_logo.svg.png', played: 19, won: 11, drawn: 3, lost: 6, gf: 38, ga: 27, gd: 11, points: 36 },
    { rank: 6, team: 'Bayer Leverkusen', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/59/Bayer_04_Leverkusen_logo.svg/100px-Bayer_04_Leverkusen_logo.svg.png', played: 19, won: 11, drawn: 2, lost: 6, gf: 38, ga: 26, gd: 12, points: 35 },
    { rank: 7, team: 'SC Freiburg', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/11/SC_Freiburg_logo.svg/100px-SC_Freiburg_logo.svg.png', played: 20, won: 7, drawn: 6, lost: 7, gf: 31, ga: 33, gd: -2, points: 27 },
    { rank: 8, team: 'Eintracht Frankfurt', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Eintracht_Frankfurt_Logo.svg/100px-Eintracht_Frankfurt_Logo.svg.png', played: 20, won: 7, drawn: 6, lost: 7, gf: 40, ga: 45, gd: -5, points: 27 },
    { rank: 9, team: '1. FC Union Berlin', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/1._FC_Union_Berlin_Logo.svg/100px-1._FC_Union_Berlin_Logo.svg.png', played: 20, won: 6, drawn: 6, lost: 8, gf: 25, ga: 33, gd: -8, points: 24 },
    { rank: 10, team: 'FC Cologne', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/15/1._FC_K%C3%B6ln_logo.svg/100px-1._FC_K%C3%B6ln_logo.svg.png', played: 20, won: 6, drawn: 5, lost: 9, gf: 29, ga: 32, gd: -3, points: 23 },
    { rank: 11, team: 'FC Augsburg', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b5/FC_Augsburg_logo.svg/100px-FC_Augsburg_logo.svg.png', played: 19, won: 5, drawn: 6, lost: 9, gf: 24, ga: 33, gd: -9, points: 21 },
    { rank: 12, team: 'Borussia Mönchengladbach', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Borussia_M%C3%B6nchengladbach_logo.svg/100px-Borussia_M%C3%B6nchengladbach_logo.svg.png', played: 19, won: 4, drawn: 7, lost: 8, gf: 19, ga: 29, gd: -10, points: 19 },
    { rank: 13, team: 'Hamburg SV', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/HSV-Logo.svg/100px-HSV-Logo.svg.png', played: 20, won: 5, drawn: 4, lost: 11, gf: 28, ga: 42, gd: -14, points: 19 },
    { rank: 14, team: 'VfL Wolfsburg', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Logo-VfL-Wolfsburg.svg/100px-Logo-VfL-Wolfsburg.svg.png', played: 19, won: 5, drawn: 4, lost: 9, gf: 22, ga: 38, gd: -16, points: 19 },
    { rank: 15, team: 'Werder Bremen', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/SV-Werder-Bremen-Logo.svg/100px-SV-Werder-Bremen-Logo.svg.png', played: 20, won: 4, drawn: 6, lost: 10, gf: 23, ga: 33, gd: -10, points: 18 },
    { rank: 16, team: 'Mainz', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Logo_Mainz_05.svg/100px-Logo_Mainz_05.svg.png', played: 20, won: 3, drawn: 5, lost: 12, gf: 18, ga: 34, gd: -16, points: 14 },
    { rank: 17, team: 'St. Pauli', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/FC_St._Pauli_Logo_2018.svg/100px-FC_St._Pauli_Logo_2018.svg.png', played: 20, won: 3, drawn: 4, lost: 13, gf: 19, ga: 45, gd: -26, points: 13 },
    { rank: 18, team: '1. FC Heidenheim 1846', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/1._FC_Heidenheim_1846_logo.svg/100px-1._FC_Heidenheim_1846_logo.svg.png', played: 19, won: 2, drawn: 5, lost: 12, gf: 16, ga: 38, gd: -22, points: 11 }
  ],
  
  'Serie A': [
    { rank: 1, team: 'Internazionale', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/100px-FC_Internazionale_Milano_2021.svg.png', played: 23, won: 18, drawn: 1, lost: 4, gf: 52, ga: 19, gd: 33, points: 55 },
    { rank: 2, team: 'AC Milan', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Logo_of_AC_Milan.svg/100px-Logo_of_AC_Milan.svg.png', played: 23, won: 14, drawn: 8, lost: 1, gf: 38, ga: 17, gd: 21, points: 50 },
    { rank: 3, team: 'Napoli', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/SSC_Neapel.svg/100px-SSC_Neapel.svg.png', played: 23, won: 14, drawn: 4, lost: 5, gf: 33, ga: 21, gd: 12, points: 46 },
    { rank: 4, team: 'Juventus', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Juventus_FC_2017_logo.svg/100px-Juventus_FC_2017_logo.svg.png', played: 23, won: 13, drawn: 6, lost: 4, gf: 39, ga: 18, gd: 21, points: 45 },
    { rank: 5, team: 'AS Roma', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f7/AS_Roma_logo_%282017%29.svg/100px-AS_Roma_logo_%282017%29.svg.png', played: 23, won: 14, drawn: 1, lost: 8, gf: 27, ga: 14, gd: 13, points: 43 },
    { rank: 6, team: 'Como', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Como_1907_Logo.svg/100px-Como_1907_Logo.svg.png', played: 23, won: 11, drawn: 8, lost: 4, gf: 37, ga: 16, gd: 21, points: 41 },
    { rank: 7, team: 'Atalanta', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/66/Atalanta_BC_logo.svg/100px-Atalanta_BC_logo.svg.png', played: 23, won: 9, drawn: 9, lost: 5, gf: 30, ga: 20, gd: 10, points: 36 },
    { rank: 8, team: 'Lazio', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/S.S._Lazio_badge.svg/100px-S.S._Lazio_badge.svg.png', played: 23, won: 8, drawn: 8, lost: 7, gf: 24, ga: 21, gd: 3, points: 32 },
    { rank: 9, team: 'Udinese', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/Udinese_Calcio_logo.svg/100px-Udinese_Calcio_logo.svg.png', played: 23, won: 9, drawn: 5, lost: 9, gf: 26, ga: 34, gd: -8, points: 32 },
    { rank: 10, team: 'Bologna', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Bologna_F.C._1909_logo.svg/100px-Bologna_F.C._1909_logo.svg.png', played: 23, won: 8, drawn: 6, lost: 9, gf: 32, ga: 30, gd: 2, points: 30 },
    { rank: 11, team: 'Sassuolo', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/38/U.S._Sassuolo_Calcio_logo.svg/100px-U.S._Sassuolo_Calcio_logo.svg.png', played: 23, won: 8, drawn: 5, lost: 10, gf: 27, ga: 29, gd: -2, points: 29 },
    { rank: 12, team: 'Cagliari', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/75/Cagliari_Calcio_1920_logo.svg/100px-Cagliari_Calcio_1920_logo.svg.png', played: 23, won: 8, drawn: 6, lost: 9, gf: 30, ga: 31, gd: -1, points: 28 },
    { rank: 13, team: 'Torino', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/Torino_FC_Logo.svg/100px-Torino_FC_Logo.svg.png', played: 23, won: 7, drawn: 7, lost: 9, gf: 28, ga: 31, gd: -3, points: 28 },
    { rank: 14, team: 'Genoa', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/72/Genoa_C.F.C._logo.svg/100px-Genoa_C.F.C._logo.svg.png', played: 23, won: 5, drawn: 8, lost: 10, gf: 27, ga: 34, gd: -7, points: 23 },
    { rank: 15, team: 'Cremonese', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/US_Cremonese_logo.svg/100px-US_Cremonese_logo.svg.png', played: 23, won: 5, drawn: 8, lost: 10, gf: 20, ga: 31, gd: -11, points: 23 },
    { rank: 16, team: 'Parma', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/17/Parma_Calcio_1913_logo.svg/100px-Parma_Calcio_1913_logo.svg.png', played: 23, won: 5, drawn: 8, lost: 10, gf: 15, ga: 30, gd: -15, points: 23 },
    { rank: 17, team: 'Lecce', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/70/US_Lecce.svg/100px-US_Lecce.svg.png', played: 23, won: 4, drawn: 6, lost: 13, gf: 13, ga: 30, gd: -17, points: 18 },
    { rank: 18, team: 'Fiorentina', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/ACF_Fiorentina.svg/100px-ACF_Fiorentina.svg.png', played: 23, won: 3, drawn: 8, lost: 12, gf: 25, ga: 36, gd: -11, points: 17 },
    { rank: 19, team: 'Pisa', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/Pisa_SC_logo.svg/100px-Pisa_SC_logo.svg.png', played: 23, won: 1, drawn: 11, lost: 11, gf: 19, ga: 40, gd: -21, points: 14 },
    { rank: 20, team: 'Hellas Verona', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Hellas_Verona_FC_logo.svg/100px-Hellas_Verona_FC_logo.svg.png', played: 23, won: 2, drawn: 8, lost: 13, gf: 18, ga: 41, gd: -23, points: 14 }
  ],
  
  'Ligue 1': [
    { rank: 1, team: 'Paris Saint-Germain', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Paris_Saint-Germain_F.C..svg/100px-Paris_Saint-Germain_F.C..svg.png', played: 20, won: 15, drawn: 3, lost: 2, gf: 43, ga: 16, gd: 27, points: 48 },
    { rank: 2, team: 'Lens', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9d/Racing_Club_de_Lens.svg/100px-Racing_Club_de_Lens.svg.png', played: 20, won: 15, drawn: 1, lost: 4, gf: 34, ga: 16, gd: 18, points: 46 },
    { rank: 3, team: 'Marseille', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Olympique_Marseille_logo.svg/100px-Olympique_Marseille_logo.svg.png', played: 20, won: 12, drawn: 3, lost: 5, gf: 46, ga: 22, gd: 24, points: 39 },
    { rank: 4, team: 'Lyon', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Olympique_lyonnais_%28logo%29.svg/100px-Olympique_lyonnais_%28logo%29.svg.png', played: 20, won: 12, drawn: 3, lost: 5, gf: 33, ga: 20, gd: 13, points: 39 },
    { rank: 5, team: 'Lille', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/62/Lille_OSC_%28logo%29.svg/100px-Lille_OSC_%28logo%29.svg.png', played: 20, won: 10, drawn: 2, lost: 8, gf: 34, ga: 30, gd: 4, points: 32 },
    { rank: 6, team: 'Stade Rennais', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/26/Stade_Rennais_F.C._logo.svg/100px-Stade_Rennais_F.C._logo.svg.png', played: 20, won: 9, drawn: 3, lost: 8, gf: 30, ga: 31, gd: -1, points: 30 },
    { rank: 7, team: 'Strasbourg', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Racing_Club_Strasbourg_Alsace_%28logo%2C_2020%29.svg/100px-Racing_Club_Strasbourg_Alsace_%28logo%2C_2020%29.svg.png', played: 20, won: 8, drawn: 6, lost: 6, gf: 31, ga: 23, gd: 8, points: 30 },
    { rank: 8, team: 'Toulouse', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Toulouse_FC_2018_logo.svg/100px-Toulouse_FC_2018_logo.svg.png', played: 20, won: 8, drawn: 7, lost: 5, gf: 27, ga: 31, gd: -4, points: 28 },
    { rank: 9, team: 'Lorient', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/FC_Lorient_Logo.svg/100px-FC_Lorient_Logo.svg.png', played: 20, won: 7, drawn: 7, lost: 6, gf: 25, ga: 31, gd: -6, points: 28 },
    { rank: 10, team: 'AS Monaco', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Logo_AS_Monaco.svg/100px-Logo_AS_Monaco.svg.png', played: 20, won: 7, drawn: 5, lost: 8, gf: 21, ga: 25, gd: -4, points: 26 },
    { rank: 11, team: 'Angers', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Angers_SCO_%28Logo%29.svg/100px-Angers_SCO_%28Logo%29.svg.png', played: 20, won: 6, drawn: 5, lost: 9, gf: 26, ga: 33, gd: -7, points: 23 },
    { rank: 12, team: 'Brest', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b3/Stade_Brestois_29_logo.svg/100px-Stade_Brestois_29_logo.svg.png', played: 20, won: 6, drawn: 4, lost: 10, gf: 26, ga: 34, gd: -8, points: 22 },
    { rank: 13, team: 'Nice', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/OGC_Nice_logo.svg/100px-OGC_Nice_logo.svg.png', played: 20, won: 5, drawn: 6, lost: 9, gf: 23, ga: 33, gd: -10, points: 21 },
    { rank: 14, team: 'Paris FC', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/62/Paris_FC_logo.svg/100px-Paris_FC_logo.svg.png', played: 20, won: 6, drawn: 4, lost: 10, gf: 16, ga: 25, gd: -9, points: 21 },
    { rank: 15, team: 'Le Havre AC', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Le_Havre_AC_%28logo%29.svg/100px-Le_Havre_AC_%28logo%29.svg.png', played: 20, won: 5, drawn: 6, lost: 9, gf: 26, ga: 34, gd: -8, points: 21 },
    { rank: 16, team: 'Nantes', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/FC_Nantes_logo.svg/100px-FC_Nantes_logo.svg.png', played: 20, won: 4, drawn: 5, lost: 11, gf: 21, ga: 46, gd: -25, points: 12 },
    { rank: 17, team: 'AJ Auxerre', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/30/AJ_Auxerre_Logo.svg/100px-AJ_Auxerre_Logo.svg.png', played: 20, won: 3, drawn: 3, lost: 14, gf: 14, ga: 29, gd: -15, points: 12 },
    { rank: 18, team: 'Metz', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/FC_Metz_Logo.svg/100px-FC_Metz_Logo.svg.png', played: 20, won: 3, drawn: 4, lost: 13, gf: 14, ga: 29, gd: -15, points: 13 }
  ]
};